name: profile-service

on:
  push:
    branches:
      - master  # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build --if-present

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ${{ secrets.APP_DIR_PRODUCT_SERVICE }}
            git pull origin master
            /home/ubuntu/.nvm/versions/node/v20.19.4/bin/npm install
            /home/ubuntu/.nvm/versions/node/v20.19.4/bin/npm run build
            /home/ubuntu/.nvm/versions/node/v20.19.4/bin/pm2 restart profile-service
